### ISSUE TITLE
Support for `model.generate`

### ISSUE THREAD

**Issue by ankrgyl** [ELS-RD/kernl#119]
I tried using `kernl` with a T5 model (`T5ForConditionalGeneration`) and was not able to call `model.generate` since `optimize_model` returns a function.

**Comment by pommedeterresautee** [comment]
would it be possible for you to follow this notebook:
https://github.com/ELS-RD/kernl/blob/main/tutorial/t5%20e2e.ipynb
?

**Comment by ankrgyl** [comment]
Sorry for the delay -- yes I can follow this notebook! I appreciate the pointer.
