### ISSUE TITLE
An general unrelated question

### ISSUE THREAD

**Issue by jinfagang** [ELS-RD/kernl#120]
Hi, ths kernl implementation is intuitive. Wanna ask if there is a way to enable triton or kernl it self to generate c++ code kernels which do a certrain operation? If so, then we can using it to generate certain op's c++ source

**Comment by gaetansnl** [comment]
In Kernl we are using Triton Python api to compile and launch kernels. If you want to directly launch kernels from C++, it is more related to triton than kernl. You might want to study how it's done in https://github.com/openai/triton/blob/master/python/triton/compiler.py or asking them if there is an easy way to do this.
You can take a look here too https://github.com/openai/triton/blob/71b46acc422594bc30d8aff80a448d8e77a8e5db/python/src/triton.cc#L497

If you can successfully call a triton kernel from C++, you can compile our kernels from `src/kernl/implementations` and use it in your project, you probably don't need the other parts of kernl.

**Comment by jinfagang** [comment]
@gaetansnl thank u, it looks like kernls get a even better perforamnce than tensorrt on some configations.
 Does it works out of box for more transformers? Such as Vit, Swin, DINO etc?

**Comment by gaetansnl** [comment]
We only tested on few text transformers, not vision. But it could be easy to add support for parts of vision transformers. For example the one you cited vit, by looking at the model code https://github.com/huggingface/transformers/blob/main/src/transformers/models/vit/modeling_vit.py#L210 we see that attention isn't very special.

It could work with our current patterns, but if it doesn't it should be not too difficult to add one. You can open an issue for the transformer you want to support.

**Comment by gaetansnl** [comment]
Feel free to reopen if you have more questions
