### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by DeqianBai** [ELS-RD/kernl#125]
when I run 
'pip install -e .'

I got the follw error:

`# pip install -e .
Obtaining file:///root/baidq/basefile/kernl
  Preparing metadata (setup.py) ... done
Collecting torchdynamo@ git+https://github.com/pytorch/torchdynamo.git@6bd5b8bb8888d5dab0b9574b20f00de975eebc72
  Cloning https://github.com/pytorch/torchdynamo.git (to revision 6bd5b8bb8888d5dab0b9574b20f00de975eebc72) to /tmp/pip-install-xbitcrmu/torchdynamo_b51b4ccfd53740999fb89c0b03e83fbb
  Running command git clone --filter=blob:none --quiet https://github.com/pytorch/torchdynamo.git /tmp/pip-install-xbitcrmu/torchdynamo_b51b4ccfd53740999fb89c0b03e83fbb
  fatal: unable to access 'https://github.com/pytorch/torchdynamo.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
  warning: Clone succeeded, but checkout failed.
  You can inspect what was checked out with 'git status'
  and retry the checkout with 'git checkout -f HEAD'

  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet https://github.com/pytorch/torchdynamo.git /tmp/pip-install-xbitcrmu/torchdynamo_b51b4ccfd53740999fb89c0b03e83fbb did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/pytorch/torchdynamo.git /tmp/pip-install-xbitcrmu/torchdynamo_b51b4ccfd53740999fb89c0b03e83fbb did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

env:
GPU:A6000
CUDA:11.4
torch:1.12.1+cu113
python: 3.9.13 

is there anyone can help me

**Comment by pommedeterresautee** [comment]
Strange, the error seems related to Git.
What is your Git version?

What happens if you do:

```shell
git clone --filter=blob:none --quiet https://github.com/pytorch/torchdynamo.git /tmp/pip-install-xbitcrmu/torchdynamo_b51b4ccfd53740999fb89c0b03e83fbb
cd /tmp/pip-install-xbitcrmu/torchdynamo_b51b4ccfd53740999fb89c0b03e83fbb
git checkout 6bd5b8bb8888d5dab0b9574b20f00de975eebc72
```

**Comment by pommedeterresautee** [comment]
Last version do not need anymore to install from git, so may work better for you :-)

**Comment by junrong1** [comment]
> when I run 'pip install -e .'
> 
> I got the follw error:
> 
> `# pip install -e . Obtaining file:///root/baidq/basefile/kernl Preparing metadata (setup.py) ... done Collecting torchdynamo@ git+https://github.com/pytorch/torchdynamo.git@6bd5b8bb8888d5dab0b9574b20f00de975eebc72 Cloning https://github.com/pytorch/torchdynamo.git (to revision 6bd5b8bb8888d5dab0b9574b20f00de975eebc72) to /tmp/pip-install-xbitcrmu/torchdynamo_b51b4ccfd53740999fb89c0b03e83fbb Running command git clone --filter=blob:none --quiet https://github.com/pytorch/torchdynamo.git /tmp/pip-install-xbitcrmu/torchdynamo_b51b4ccfd53740999fb89c0b03e83fbb fatal: unable to access 'https://github.com/pytorch/torchdynamo.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated. warning: Clone succeeded, but checkout failed. You can inspect what was checked out with 'git status' and retry the checkout with 'git checkout -f HEAD'
> 
> error: subprocess-exited-with-error
> 
> × git clone --filter=blob:none --quiet https://github.com/pytorch/torchdynamo.git /tmp/pip-install-xbitcrmu/torchdynamo_b51b4ccfd53740999fb89c0b03e83fbb did not run successfully. │ exit code: 128 ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error
> 
> × git clone --filter=blob:none --quiet https://github.com/pytorch/torchdynamo.git /tmp/pip-install-xbitcrmu/torchdynamo_b51b4ccfd53740999fb89c0b03e83fbb did not run successfully. │ exit code: 128 ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.`
> 
> env: GPU:A6000 CUDA:11.4 torch:1.12.1+cu113 python: 3.9.13
> 
> is there anyone can help me

I had the same issue, did you fix it?

**Comment by EnesGokceDS** [comment]
> Last version do not need anymore to install from git, so may work better for you :-)

I have been trying this approach to install but still getting the same error
```pip install 'git+https://github.com/ELS-RD/kernl' --extra-index-url https://download.pytorch.org/whl/nightly/cu117```
