### ISSUE TITLE
RuntimeError: GPU compute capability 8.0 (Ampere) or higher is required to install kernl

### ISSUE THREAD

**Issue by YontiLevin** [ELS-RD/kernl#133]
Im trying to test this on nvidia T4 and V100 gpus, but it fails with the above error.
they have 7.5 and 7 compute capacity respectively.
any plans to support these GPU types in the future?
thanks

**Comment by pommedeterresautee** [comment]
This is due to the way some operations are supported on Triton language. The language is going through a complete rewrite. It may help fix those issues. They will probably deliver in 1-2 months. In between there is nothing we can do.

**Comment by philschmid** [comment]
@pommedeterresautee if I understand your answer correctly. `kernl` might support < Ampere architecture when `triton` supports them easier.

**Comment by pommedeterresautee** [comment]
Yes, also we discuss with cutlass team about next big release and what will be doable, etc.

**Comment by philschmid** [comment]
Awesome! keep up the good work! That's the first project/package which makes those features accessible! 🤗
