### ISSUE TITLE
Would it be possible to use kernl to speed up Stable Diffusion?

### ISSUE THREAD

**Issue by 0xdevalias** [ELS-RD/kernl#141]
I don't know deeply what would be involved in this, but I was wondering if kernl would have application in speeding up StableDiffusion at all?

Crossposted:

- https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/4096
- https://github.com/huggingface/diffusers/issues/1094

**Comment by gaetansnl** [comment]
We are currently investigating Whisper, StableDiffusion is the next :)

**Comment by jonathlela** [comment]
We won't support stable diffusion in the near future.
