### ISSUE TITLE
why is model.generate repeated 10 times in t5 generate example?

### ISSUE THREAD

**Issue by GongCQ** [ELS-RD/kernl#145]
in the t5 e2e example, the last code block,
https://github.com/ELS-RD/kernl/blob/main/tutorial/t5%20e2e.ipynb

    **for _ in range(10):
        model.generate(
            inputs=input_ids["input_ids"],
            min_length=22,
            max_length=22,
        )**

does it mean that we have to repeat the generate 10 times to ensure the warmup has been completed?

**Comment by pommedeterresautee** [comment]
10 is an arbitrary number, it is to push the gpu to make it clock at its peak speed otherwise your first tokens may be generated at a different clock frequency than the next ones. There are slightly cleaner way to do that like waiting génération time stabilize, but repeating 10 generations is good enough for a notebook :-)

**Comment by GongCQ** [comment]
> 



> 10 is an arbitrary number, it is to push the gpu to make it clock at its peak speed otherwise your first tokens may be generated at a different clock frequency than the next ones. There are slightly cleaner way to do that like waiting génération time stabilize, but repeating 10 generations is good enough for a notebook :-)

when I remove the code of this repeat generation, the subsequent model.generate() may consume too much time， 3 minutes or more.  Is that a problem? or it's just expected. 

tks!

**Comment by pommedeterresautee** [comment]
it's expected, during the warmup:
- kernels are tuned and compiled (JIT)
- CUDA graphs is written
- GPU goes to full speed

1/ and 2/ takes time. We expect to improve things by:
- saving and reusing compiled compiled kernels
- using another endpoint of triton to lower the CPU overhead (we are already working on that one)
We hope that at some point, warmup will be fast, and for those who wants it, not even needed because CPU overhead is low enough to not have to leverage CUDA graphs.

**Comment by GongCQ** [comment]
It seems that the warmup action does not only occur on the first execution for model.generate().

in this code, model.generat() is executed 3 times in the loop statement.  but I found that each execution consume 3 ~ 5 minutes, it seems that the warmup occurs on every execution for model.generate(), not only the first. 

because it's named as "warmup", I should exepected that it occurs only once. Are there any details that need to be optimized?

` en_text = 'Trade liberalization, entry of WTO and agricultural development in China.'
en_text2 = 'In modem hydraulic engineering , the river training schemes are mainly decided by movable-bed model studies'
en_text3 = 'In accordance with API specifications,'

input_ids = tokenizer(en_text, return_tensors="pt", pad_to_multiple_of=8, padding=True).to(device)
input_ids2 = tokenizer(en_text2, return_tensors="pt", pad_to_multiple_of=8, padding=True).to(device)
input_ids3 = tokenizer(en_text3, return_tensors="pt", pad_to_multiple_of=8, padding=True).to(device)
for ii in [input_ids2, input_ids, input_ids3]:
    start = time.perf_counter()
    print('a %s' % dt.datetime.now())

    output = model.generate(
        inputs=ii["input_ids"],
        min_length=10,
        max_length=128,
    )
    torch.cuda.synchronize()

    latency_optimized = time.perf_counter() - start   
    print('b %s' % dt.datetime.now())     

    trans_text = tokenizer.decode(output[0], skip_special_tokens=True, clean_up_tokenization_spaces=True)
    print('c %s' % dt.datetime.now())            
    print('model gen consume: %s' % latency_optimized)
    print('[tr] %s' % trans_text)
    print()`

**Comment by pommedeterresautee** [comment]
you are right, it happens only once.
The thing is that in the notebook the encoder is not warmed, only the decoder. It's that way to keep notebook simple and fast to run, but I note that it may create some confusion...

**Comment by shengzhang37** [comment]
Hello, for the item "saving and reusing compiled compiled kernels" (https://github.com/ELS-RD/kernl/issues/145#issuecomment-1299748671). Is it savable now? Thanks

**Comment by ayoub-louati** [comment]
Hello @shengzhang37, we are still working on it (saving compiled kernels) and we hope that it will be ready soon.

**Comment by shengzhang37** [comment]
Hello @ayoub-louati  Thank you for the information. Do you have a time plan for it? I can help test saving compiled kernels as well.

**Comment by ayoub-louati** [comment]
Hello @shengzhang37, thanks for proposing your help, currently, we are working on it but as you know since it is a vacation period so it might take a little more time.

**Comment by joehoover** [comment]
@ayoub-louati, I'm also interested in saving compiled kernels. Is there an issue I can track if that work has not been merged?
