### ISSUE TITLE
No matching distribution found

### ISSUE THREAD

**Issue by arun-rangarajan** [ELS-RD/kernl#149]
Running into an error during install:

```
pip install -e . --extra-index-url https://download.pytorch.org/whl/nightly/cu117 --pre
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/nightly/cu117
Obtaining file:///C:/Users/ab/Desktop/kernl
  Preparing metadata (setup.py) ... done
ERROR: Could not find a version that satisfies the requirement triton==2.0.0.dev20221001 (from kernl) (from versions: none)
ERROR: No matching distribution found for triton==2.0.0.dev20221001
```

I thought this happened since triton==2.0.0.dev20221001 is a pre-release version, but the error happens even with `--pre` added.

**Comment by pommedeterresautee** [comment]
Which version of Python are you using?

**Comment by arun-rangarajan** [comment]
Python 3.9.13

**Comment by pommedeterresautee** [comment]
Oh, it's Windows. Triton team is probably not releasing wheel for this OS (they also do not do it for Python 3.10 and still it works).
If really you want Windows support, I would try to install Triton from sources first, then Kernl.
Maybe better to just launch the lib in the Ubuntu/Linux mode (sorry I am quite a newbie in Windows things) if possible for you (or through Docker).
