### ISSUE TITLE
Support custom transformer implementations

### ISSUE THREAD

**Issue by CodeJjang** [ELS-RD/kernl#152]
Hi, it is unclear from the docs if custom transformers implementations are also supported, or only implementations from the official transformers package?

**Comment by gaetansnl** [comment]
Hello, Sorry docs are still missing.
I'll explain how to support a model not currently supported i.e that contains operations not currently replaced with fused kernels

You can see here https://github.com/ELS-RD/kernl/blob/f22b39ccba537ca06e4f899ff483949e88eb860a/src/kernl/model_optimization.py#L36 what we do to replace the forward in the model.

It calls this function for each graph generated by torchdynamo https://github.com/ELS-RD/kernl/blob/f22b39ccba537ca06e4f899ff483949e88eb860a/src/kernl/model_optimization.py#L32 The purpose of `dynamo_backend_ofi` is to find pattern in the fx graph, and replace them with an otpimized version. `cuda_graphs_wrapper` is just to use cuda graphs.

So if you have custom model
1. You need to find the pattern you want to replace (attention, layer norm, linear, or anything if you can write triton kernel for it)
2. Replace the pattern in the fx graph

For the first step you can add a print after graph tracing
```python
def dynamo_backend_ofi(gm: torch.fx.GraphModule, assume_causal=False):
    normalize_operators(gm)
    remove_dropout(gm)
    fuse_attention_pattern_1(gm, assume_causal)
    fuse_attention_pattern_2(gm, assume_causal)
    replace_all_linear(gm)

    print(graph_report(gm)) #<------ to print table
    print(gm.code) # to print the code directly
   

    return gm

```

You will then see in the console, when you run the model, the graph getting created by torchdynamo

In almost all transformers you will see something like this for example, the attention part.

```python
        transpose_10 = k.transpose(-1, -2)
        matmul_20 = torch.matmul(q, transpose_10)
        truediv_10 = matmul_20 / 8.0
        add_30 = truediv_10 + attention_mask
        softmax_10 = torch.nn.functional.softmax(add_30, dim=-1)
        matmul_21 = torch.matmul(softmax_10, v)
```

You can then create a pattern that replace this part with the attention kernel. `attention_wrapper` is just used to avoid tracing inside the kernel function.

```python
def fuse_attention_pattern_3(gm: torch.fx.GraphModule, is_causal: bool):
    def pattern(q, k, attention_mask, v):
        transpose_10 = k.transpose(-1, -2)
        matmul_20 = torch.matmul(q, transpose_10)
        truediv_10 = matmul_20 / 8.0
        add_30 = truediv_10 + attention_mask
        softmax_10 = torch.nn.functional.softmax(add_30, dim=-1)
        matmul_21 = torch.matmul(softmax_10, v)
        return matmul_21

    def replace(q, k, attention_mask, v):
        output = torch.empty_like(q)
        output = attention_wrapper(q, k, v, output, 1 / 8.0, is_causal, attention_mask)
        return output

    replace_pattern(gm, pattern, replace)
```

As you can see we define two functions (pattern and replace) defining two patterns. replace_pattern replace the pattern in the fx graph.

Then you just need to add your replacement function 
```python
def _compiler(gm: torch.fx.GraphModule, example_inputs: List[torch.Tensor]):
    dynamo_backend_ofi(gm)
    fuse_attention_pattern_3(gm) #<-------
    return cuda_graphs_wrapper(gm, example_inputs, pool=_pool)
```

You can take a look here, to see how we added rmsnorm support for t5 https://github.com/ELS-RD/kernl/pull/107/files

Don't hesitate to ask more questions :)

**Comment by gaetansnl** [comment]
feel free to reopen if you have more questions
