### ISSUE TITLE
Torchdynamo + Inductor faster than kernl in t5 e2e example?

### ISSUE THREAD

**Issue by wangjunhaoumich** [ELS-RD/kernl#232]
To check performance between 
- Torchdynamo + Inductor
- kernl
I edited the t5 e2e example notebook [here](https://github.com/wangjunhaoumich/compare_inference/blob/main/kernl_repo/compare/compare_kernl.ipynb) to check inference speed of vanilla Torchdynamo + Inductor. i.e.
```
# dynamo inference mode
with torch.inference_mode():
    start = time.time()
    for _ in range(10):
        output = model.generate2(
            inputs=input_ids["input_ids"],
            min_length=22,
            max_length=22,
        )
        print(tokenizer.decode(output[0], skip_special_tokens=True, clean_up_tokenization_spaces=True))
    end = time.time()
    print(f'{(end - start) / 10} s / inference')
```
I got 0.07s / inference for vanilla Torchdynamo + Inductor, versus kernl's 0.092s / inference.

This is for `T5-base`, on GTX-3090-24GB in VScode dev container started in Windows wsl2.

**Comment by pommedeterresautee** [comment]
Thank you @wangjunhaoumich for your message.

I had a rapid look on the notebook and it seems to me that `model.generate2 = torchdynamo.optimize("inductor")(model.generate)` may not be a good idea.
`generate` method includes encode+decoder, and, I think, the eager/beam search step!
Therefore I would expect to not be able to adapt to an input different from the one used during the warmup as it should always replay the very same series of CUDA operations (for instance, for each step it will always choose the same nth token, whatever the input).

BTW note that the T5 notebook in this repo requires the encoder and the decoder to be warmed up which is not very practical IRL.. (but at least it works with new inputs :-) ) We are working on those things.

**Comment by Oxi84** [comment]
It does not work at all with torchdynamo. All i get is an error.

**Comment by wangjunhaoumich** [comment]
Thanks @pommedeterresautee !

To verify whether ` vanilla dynamo + inductor would be able to adapt to an input different from the one used during the warmup as it should always replay the very same series of CUDA operations (for instance, for each step it will always choose the same nth token, whatever the input)` I updated my notebook on a different branch [here](https://github.com/wangjunhaoumich/compare_inference/blob/investigate-dynamo-kernl/kernl_repo/compare/compare_kernl.ipynb), to summarize the observations:

- dynamo+inductor does adapt to a different input under some conditions
    - input is the same length (padding solves this problem)
    - `.generate2()` doesn't use beam_search since it wasn't used during warm-up, for example, can use `do_sample` instead of default `greedy_search`
- `kernl` seems to output all 0s in the example using `t5-base`, could be a quantization problem?
- The speed gap still exists between dynamo+inductor vs. kernl

Maybe I missed something?
