### ISSUE TITLE
Accelerate warmup IRL?

### ISSUE THREAD

**Issue by JaheimLee** [ELS-RD/kernl#242]
IRL, batch size or sequence length usually varies form one to hundreds, especially for generation model. So the warmup may cost several days. Is it possible to reduce the time cost in the future?

**Comment by pommedeterresautee** [comment]
We just merged a 3x warmup time reduction.
The use case is for whisper where encoder output shape is fixed.

For other models where encoder output shape is not fixed, we need dynamic shape of Dynamo to work as expected. For now it seems to be a bit buggy... but PyTorch team is working on it AFAIK. Second point is to use another end point of Triton with less cpu overhead, this work is ongoing 
Cc @ayoub-louati

**Comment by JaheimLee** [comment]
Hi, I find a compiler named [BladeDISC](https://github.com/alibaba/BladeDISC). I'm not sure whether it can help to speed up or not. You can have a look.
