### ISSUE TITLE
Where can I install the software (on which hosting I can try it) 

### ISSUE THREAD

**Issue by Oxi84** [ELS-RD/kernl#253]
### Description

So far I have tried vast.ai and runpod.io and i wasn't able to install the software. On runpod i was able to install but then then it does not work, for some cuda error.

Is there any hosting where it is possible to install it? I do not get it, do i need cuda 1.7 for that? I know I need cards newer than rtx 2080 but I have that, only installation does not work.

### Self-service

- [ ] I would be willing to contribute to this issue myself.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pommedeterresautee** [comment]
Would it be possible for you to use a cloud like Azure or AWS?
The GPU generation needs to be >= Ampere (which is not the case of the rtx 2080) and CUDA >= 11.4

**Comment by Oxi84** [comment]
I never tried Azure, is it possible to install this on some instances? 

Did you have any speedup with this? I have been trying onxx on CPU and it does not work at all if it is already optimised with longer batches, beam search of 4 and sequence lenght of 15-20. Nothing bring any speed-up it was just waste of timex except that I know it does not work.

**Comment by pommedeterresautee** [comment]
This library is only for recent Nvidia GPUs, may be later for AMD / Intel GPUs.
It will indeed not bring any speed up on CPUs.
You may want to try Inductor from PyTorch 2.0 for that (they convert eager models to compiled C++), it should bring some speedup, at least during training.
