### ISSUE TITLE
version is still 0.1.0

### ISSUE THREAD

**Issue by JaheimLee** [ELS-RD/kernl#273]
You have updated kernl to 0.2.0. But it still shows 0.1.0 using `pip install -e . --extra-index-url https://download.pytorch.org/whl/nightly/cu117`
```
Installing collected packages: kernl
  Attempting uninstall: kernl
    Found existing installation: kernl 0.1.0
    Uninstalling kernl-0.1.0:
      Successfully uninstalled kernl-0.1.0
  Running setup.py develop for kernl
Successfully installed kernl-0.1.0
```

**Comment by pommedeterresautee** [comment]
Thanks @JaheimLee , we were so happy to release that we forgot this detail :-)
CC @jonathlela

**Comment by jonathlela** [comment]
Thanks for pointing this out, we've updated the CI so it won't happen again.
