### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by p-christ** [ELS-RD/kernl#293]
### Description

When I clone the repository and then run

`pip install -e . --extra-index-url https://download.pytorch.org/whl/nightly/cu117`

i'm getting the following error:

```
#0 5.391   Preparing metadata (setup.py): finished with status 'done'
#0 6.663 Collecting triton==2.0.0.dev20221202
#0 6.866   Downloading triton-2.0.0.dev20221202-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.7 MB)
#0 11.03      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.7/18.7 MB 4.2 MB/s eta 0:00:00
#0 13.62 Collecting torch==2.0.0.dev20230128+cu117
#0 13.67   Downloading https://download.pytorch.org/whl/nightly/cu117/torch-2.0.0.dev20230128%2Bcu117-cp310-cp310-linux_x86_64.whl (1826.5 MB)
#0 381.7 Killed
------
ERROR: failed to solve: executor failed running [/bin/sh -c git clone https://github.com/ELS-RD/kernl.git      && cd kernl      && pip install -e . --extra-index-url https://download.pytorch.org/whl/nightly/cu117      && cd ..]: exit code: 137
```

Does anyone know how to fix this?

### Steps to reproduce

Clone the repository and then run
`pip install -e . --extra-index-url https://download.pytorch.org/whl/nightly/cu117`

### Expected Behavior

It should have installed the repository

### Actual Behavior

It fails

### Your environment

My Dockerfile:

```
FROM  --platform=linux/amd64  nvidia/cuda:11.3.0-runtime-ubuntu20.04 

# Install base utilities
RUN apt-get update && \
    apt-get install -y wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install miniconda
ENV CONDA_DIR /opt/conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
     /bin/bash ~/miniconda.sh -b -p /opt/conda

# Put conda in path so we can use conda activate
ENV PATH=$CONDA_DIR/bin:$PATH


RUN conda install -y cudatoolkit


RUN apt-get -y update \
    && apt-get install -y software-properties-common \
    && apt-get -y update \
    && add-apt-repository universe \
    && apt-get install --assume-yes git
RUN apt-get -y update
RUN apt-get -y install python3
RUN apt-get -y install python3-pip


# Install libraries
RUN pip install -U pip

RUN git clone https://github.com/ELS-RD/kernl.git \
     && cd kernl \
     && pip install -e . --extra-index-url https://download.pytorch.org/whl/nightly/cu117 \
     && cd .. 


COPY ./requirements.txt ./
RUN python3 -m pip install --default-timeout=900 -r requirements.txt
RUN rm ./requirements.txt
    

# Setup container directories
RUN mkdir /app

# Copy local code to the container
COPY ./app /app


# launch server with gunicorn
WORKDIR /app
EXPOSE 8080
CMD ["gunicorn", "main:app", "--timeout=0",  \
     "--workers=1", "--threads=4", "--bind=0.0.0.0:8080"]

```

### Self-service

- [ ] I would be willing to help fix this bug myself.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pommedeterresautee** [comment]
Did the download of PyTorch started?

**Comment by p-christ** [comment]
Yep it started but then this error showed

**Comment by pommedeterresautee** [comment]
May I ask you if you can install PyTorch nightly pinned in requirements directly? Just to understand if it's related to Kernl setup file or a more generic problem

**Comment by p-christ** [comment]
Ok yes if I just run this on its own

`python3 -m pip install torch==2.0.0.dev20230128+cu117 --extra-index-url `

I get the same error below.  So the problem is the torch version rather than kernl -- do you have any ideas how i can get around this problem?

` => ERROR [10/14] RUN python3 -m pip install torch==2.0.0.dev20230128+cu117 --extra-index-url https://download.pytorch.org/whl/nightly/cu117                      195.8s
------                                                                                                                                                                   
 > [10/14] RUN python3 -m pip install torch==2.0.0.dev20230128+cu117 --extra-index-url https://download.pytorch.org/whl/nightly/cu117:                                   
#0 3.238 Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/nightly/cu117                                                                     
#0 5.097 Collecting torch==2.0.0.dev20230128+cu117                                                                                                                       
#0 5.135   Downloading https://download.pytorch.org/whl/nightly/cu117/torch-2.0.0.dev20230128%2Bcu117-cp310-cp310-linux_x86_64.whl (1826.5 MB)
#0 194.8 Killed
------
ERROR: failed to solve: executor failed running [/bin/sh -c python3 -m pip install torch==2.0.0.dev20230128+cu117 --extra-index-url https://download.pytorch.org/whl/nightly/cu117]: exit code: 137`

**Comment by pommedeterresautee** [comment]
Would it be possible for you to use a more modern docker image base?
Also, what version of Python conda is running?

**Comment by flozi00** [comment]
The killed return often happens while out of memory or out of space

**Comment by p-christ** [comment]
> The killed return often happens while out of memory or out of space

This was why, my docker was running out of memory. I fixed it by changing the settings in docker to allow it to use more memory. thanks a lot
