### ISSUE TITLE
Add pattern to replace rmsnorm in T5

### ISSUE THREAD

**Issue by pommedeterresautee** [ELS-RD/kernl#94]
we only replace layernorm for now.
T5 is using a simplified version of layernorm without any mean computation.
Our layernorm kernel supports both cases.

task: replace rmsnorm in T5

Would be nice if we remove default parameters of layernorm (put in place to not change layernorm pattern and still support rmsnorm) by setting all args in the replace pattern.

**Comment by gaetansnl** [comment]
@pommedeterresautee already done
